# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lesson_quiz
    username: postgres
    password: admin
  # JPA properties
  jpa:
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        ddl-auto: validate
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    open-in-view: false
  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    
springdoc:
  swagger-ui:
    path: /swagger-ui